### ISSUE TITLE
plotting causing core dump when using profiler

### ISSUE THREAD

**Issue by chrisiacovella** [choderalab/modelforge#325]
Both @MarshallYan  and I have encountered instances where training crashes due to issue with tkinter library (which is the python interface to tcl/tk).  This library is used under the hood by things like matplotlib, called during the plot generation. 

One of the errors is below: 

`Exception ignored in: <function Variable.__del__ at 0x7fb362735300>
Traceback (most recent call last):
  File "/home/shuaiy/miniforge3/envs/modelforge/lib/python3.11/tkinter/__init__.py", line 410, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop

Exception ignored in: <function Variable.__del__ at 0x7fb362735300>
Traceback (most recent call last):
  File "/home/shuaiy/miniforge3/envs/modelforge/lib/python3.11/tkinter/__init__.py", line 410, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
`

This only occurs when we have profilers set.  This seems to happen at different "times" (i.e., epochs).  E.g., crashing on epoch 18 one time 48 the next, 97 a third time (when using the simple profiler) 

Since this only happens during profiling, which typically will only typically run a few steps (and it seems to happen randomly), I'm not sure how much effort we should put into trying to better diagnose this.  If it crashes too early to get data, one can reduce number of training steps or simple try running again.

**Comment by chrisiacovella** [comment]
Additional note, this occurs when using tensor board locally on my machine (which takes in the matplotlib figures and handles things after that...it might not happen in wandb).  @MarshallYan tried setting the matplotlib backend to `agg` and that solves the issue.  Will push a quick PR for this.

**Comment by chrisiacovella** [comment]
`import matplotlib
matplotlib.use("Agg")
`

Added to the top of training.py
